project:
  type: book
  output-dir: _book

book:
  title: "Measure, Integration & Real Analysis (Sheldon Axler) - Notes"
  author: "Phong Nguyen"
  reader-mode: true

  page-footer:
    left: |
      Measure, Integration & Real Analysis (Sheldon Axler) - Notes 
      are written by Phong Nguyen and Trung Tran
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-url: https://github.com/noro-math/Measure-Integration-Real-Analysis-Notes-Axler-S-.git
  repo-branch: master
  repo-actions: [edit,issue]

  chapters:
    - index.qmd
    - part: "Supplement"
      chapters:
        - Oct5.qmd
        - Oct29.qmd
  

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand




