---
author: "Phong Nguyen"
date: "Oct 5 2025"
format: html
---

# Sep - Oct 5 Notes

## INTRODUCTION

The following are notes for Supplement for the textbook *Measure, Integration & Real Analysis* by Sheldon Axler.

This week's notes go over **Section A - Complete Ordered Field**


## Definition

A *field* is a set $\mathbb{F}$ along with operations of addition and multiplication on F that have the following properties (Alex, S):

+ **commutativity**: $a+b = b+a$ and $ab = ba\forall a,b \in\mathbb{F}$

+ **associativity**: $(a+b)+c = a+(b+c)$ and $(ab)c = a(bc)\forall a,b,c \in \mathbb{F}$

+ **distributive property**: $a(b+c) = ab + ac,\thinspace \forall a,b \in \mathbb{F}$

+ **additive identity**: There exists an element 0 $\in F$ such that $a+0=a, \thinspace \forall a \in \mathbb{F}$
+ **additive inverse**: $\forall a \in \mathbb{f}$, there exists an element $-a \in \mathbb{F}$ such that $a+(-a)=0.$ 
+ **multiplication identity:** There exists an element $1 \in \mathbb{F}$ such that $1 \neq 0$ and $a1=a, \thinspace \forall a \in \mathbb{F}.$
+ **multiplication inverse:** $\forall a \in \mathbb{F}$ with $a \neq 0$, there exists an element $a^{-1} \in \mathbb{F}$ such that $aa^{-1}=1.$

***0.3 properties of the additive inverse in a field***

(a) for each $a \in \mathbb{F},\thinspace$ the additive inverse of $a$ is unique (thus the notation $-a$ makese sense)
(b) $-(-a) = a$ for each $a \in \mathbb{F}$
(c) $(-1)a = -a, \thinspace \forall a \in \mathbb{F}$

***Proof (0.3)***

***Part (a)*** We have the additive inverse property: $$a + (-a) = 0$$
Suppose there exists an additive inverse of $a = b, \thinspace b \neq -a. \thinspace$
We have: $$a + b = 0$$
Add LHS and RHS by $(-a)$:
$$a+b + -a = -a$$
Using additive property of $a +(-a) = 0$:
$$0 + b = -a$$
$$\rightarrow b = -a$$ 
Impossible since $b\neq (-a). \thinspace$ So additive inverse of $a = -a$ is unique.

***Part (b)*** We have the additive inverse property: $$a + (-a) = 0$$
Subtract LHS and RHS by (-a): $$ a + (-a) - (-a) = 0 - (-a)$$
$$ a = -(-a)$$

***Part (c)*** We have 1 and the additive inverse of 1 = (-1) (Additive Inverse property)
We have: $$1 + (-1) = 0$$
Multiply LHS and RHS by a:$$a1 + (-1)a = 0a$$
Using multiplication identity $a1 = a$ and $a0 = 0$: $$a +(-1)a = 0$$
$$\rightarrow (-1)a = -a$$

***analogous properties of the multiplication inverse***

(a) for each $a \in \mathbb{F},\thinspace$ the multiplication inverse of $a$ is unique (thus the notation $a^{-1}$ makese sense)
(b) $(a^{-1})^{-1} = a$ for each $a \in \mathbb{F}$
(c) $1 : a = a^{-1}, \thinspace \forall a \in \mathbb{F}$

***Part (a)*** We have the multiplication inverse property $aa^{-1} = 1$
Suppose there exists a multiplication inverse of $a=b, b \neq a^{-1}$. We have $$ab = 1$$
$$\rightarrow ab = aa^{-1}$$
Divide LHS and RHS by a:  $$b=a^{-1}$$
Impossible since $b \neq a^{-1}$. So the multiplication inverse of any $a$ is unique.

***Part (b)***
We have the multiplication inverse property: $$aa^{-1} = 1$$
Raise LHS and RHS to $-1$ $a$: $$(aa^{-1})^{-1} = 1^{-1}$$
$$\rightarrow a^{-1}(a^{-1})^{-1} = 1$$
Using multiplication inverse property: $$a^{-1}(a^{1})^{-1} = aa^{-1}$$
Divide LHS and RHS by $a^{-1}$: $$(a^{-1})^{-1} = a$$

***Part (c)***
We have the multiplication inverse property: $$aa^{-1} = 1$$
We have: $$a^{-1} = a^{-1}$$
$$a^{-1}1 = a^{-1}$$
Using multiplication inverse property: $$a^{-1}(aa^{-1}) = a^{-1}$$
Using associativity property: $$(a^{-1}a)a^{-1} = a^{-1}$$
We have $(aa^{-1}) = (a/a) = a$
$$\Rightarrow (a/a)a^{-1} = a^{-1}$$
$$(aa^{-1})/a=a^{-1}$$
$$\rightarrow 1/a=a^{-1}$$.

***3*** Suppose $\mathbb{F} is a field and $a,b \in \mathbb{F}$. Prove that $(-a)(-b)=ab$.

***Proof***
We have the additive inverse property: $$a+(-a)=0$$
Multiply LHS and RHS by b: $$(a+(-a))b=0b$$
$$ab+(-a)b=0$$
$$ab = -(-a)b$$
$$\rightarrow ab = (-a)(-b)$$

***4*** Suppose $\mathbb{F}$ is a field and $a,b,c \in \mathbb{F}$ with $b \neq 0$ and $c \neq 0$. Prove that $$\frac{ac}{bc} = \frac{a}{b}$$

***Proof***
We have: $$\frac{ac}{bc} = (ac)(bc)^{-1} = ac(b^{-1})(c^{-1})$$
$$\rightarrow \frac{ac}{bc} = a(c^{1}c^{-1})b^{-1}$$
$$\rightarrow \frac{ac}{bc} = a1\frac{1}b = \frac{a}{b}$$

***5*** Suppose $\mathbb{F}$ is a field and $a,b,c \in \mathbb{F}$ with $b \neq 0$ and $c \neq 0$. Prove that $$\frac{a}{b}-\frac{c}{d}=\frac{ad-bc}{bd}$$

***Proof*** We have: $$\frac{a}{b}-\frac{c}{d} = ab^{-1} - cd^{-1}$$
Using multiplication identity $a1 = a$:
$$\rightarrow \frac{a}{b}-\frac{c}{d} = ab^{-1}1 - cd^{-1}1 $$
Using multiplication inverse property with $dd^{-1}$ and $bb^{-1}$
$$\frac{a}{b}-\frac{c}{d} = ab^{-1}dd^{-1} - cd^{-1}bb^{-1}$$
$$\frac{a}{b}-\frac{c}{d} = (b^{-1}d^{-1})(ad - cb)$$
$$\frac{a}{b}-\frac{c}{d} = (ad-cb)(bd)^{-1} = \frac{ad-cb}{bd}.$$

Block math:  
$$
\int_0^\infty e^{-x^2} \, dx = \frac{\sqrt{\pi}}{2}
$$

<Aligned steps:  
$$
\begin{align}
f(x) &= x^2 + 2x + 1 \\
     &= (x+1)^2
\end{align}
$$>


***6*** Suppose $\mathbb{F}$ is a field and $a,b,c,d \in \mathbb{F}$ with $b \neq 0$ $c \neq 0$, and $d \neq 0$. Prove that $$\frac{a}{b} \div \frac{c}{d} = \frac{ad}{bc}$$
***Proof*** We have: $$\frac{a}{b} \div \frac{c}{d} = ab^{-1}(cd^{-1})^{-1} = ab^{-1}c^{-1}d$$
Using associativity property: $$ab(c^{-1}d^{-1}) = ad(cd)^{-1} = \frac{ad}{cd}$$

